name: Testing

on:
  push:
    branches:
      - main

env:
  SECRET: "i4Yx6bmTJBRVLWub97qJqull3xZVIak4wz5P4x5HudIqnQ9X56x7befQAvqgGEdk5LOD0vqwomiZZb+OmTvTQQ=="
  KEYNAME: "keytest"

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.15'
    - name: Define enviroment variables
      run: |
        echo "Tsig key name > ${{env.KEYNAME }}"
        echo "Tsig secret > ${{ env.SECRET }}"
    - name: Deploy powerdns auth docker image
      run: |
        sudo docker run -d -p 5353:53/udp -p 5353:53/tcp --name=powerdns --volume=$PWD/testdata/pdns.conf:/etc/powerdns/pdns.d/pdns.conf:ro powerdns/pdns-auth-44
        sudo netstat -anp |grep 5353
    - name: Configure powerdns
      run: |
        sudo docker exec powerdns pdnsutil create-zone test.internal ns1.test.internal
        sudo docker exec powerdns pdnsutil import-tsig-key ${KEYNAME} hmac-sha256 ${SECRET}
        sudo docker exec powerdns pdnsutil set-meta test.internal TSIG-ALLOW-DNSUPDATE ${KEYNAME}
        sudo docker exec powerdns pdnsutil set-meta test.internal TSIG-ALLOW-AXFR ${KEYNAME}
        sudo docker exec powerdns pdnsutil set-meta test.internal ALLOW-DNSUPDATE-FROM 0.0.0.0/0