name: Testing

on:
  push:
    branches:
      - master
      
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.15'
    - name: Install pdns-server
      run: |
        sudo apt-get install -y pdns-server pdns-tools pdns-backend-sqlite
    - name: Configure the pdns server
      run: |
        sudo systemctl status pdns
        sudo /usr/sbin/pdns_server --version