name: Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - master

env:
  PDNSGLSB_DNSUPDATE_SERVER: "127.0.0.1"
  PDNSGLSB_DNSUPDATE_PORT: "5353"
  PDNSGLSB_DNSUPDATE_KEYALGORITHM: "hmac-sha256"
  PDNSGLSB_DNSUPDATE_KEYSECRET: "i4Yx6bmTJBRVLWub97qJqull3xZVIak4wz5P4x5HudIqnQ9X56x7befQAvqgGEdk5LOD0vqwomiZZb+OmTvTQQ=="
  PDNSGLSB_DNSUPDATE_KEYNAME: "keytest."
  TF_ACC: "true"
jobs:
  testing:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'
    - name: Deploy powerdns auth docker image
      run: |
        sudo docker run -d -p 5353:53/udp -p 5353:53/tcp --name=powerdns --volume=$PWD/testdata/pdns.conf:/etc/powerdns/pdns.d/pdns.conf:ro powerdns/pdns-auth-44
        sudo netstat -anp |grep 5353
    - name: Configure powerdns
      run: |
        sudo docker exec powerdns pdnsutil create-zone test.internal ns1.test.internal
        sudo docker exec powerdns pdnsutil import-tsig-key ${PDNSGLSB_DNSUPDATE_KEYNAME} hmac-sha256 ${PDNSGLSB_DNSUPDATE_KEYSECRET}
        sudo docker exec powerdns pdnsutil set-meta test.internal TSIG-ALLOW-DNSUPDATE ${PDNSGLSB_DNSUPDATE_KEYNAME}
        sudo docker exec powerdns pdnsutil set-meta test.internal TSIG-ALLOW-AXFR ${PDNSGLSB_DNSUPDATE_KEYNAME}
        sudo docker exec powerdns pdnsutil set-meta test.internal ALLOW-DNSUPDATE-FROM 0.0.0.0/0
    - name: Running tests
      run: |
        go test ./pdnsgslb/