name: Testing

on:
  push:
    branches:
      - main
      
jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.15'
    - name: Install pdns-server
      run: |
        sudo apt-get install -y wget net-tools
        sudo apt-get install -y pdns-server pdns-tools pdns-backend-sqlite3
    - name: Configure the pdns server
      run: |
        sudo systemctl stop systemd-resolved
        sudo systemctl status pdns
        sudo /usr/sbin/pdns_server --version
        sudo cat /etc/powerdns/pdns.conf